name = "neptune"
main = "src/index.ts"
compatibility_date = "2026-05-30"

[vars]
REUSE_CAPTCHA = "true"
RELEASE_CHANNEL_ID = "-1003921429655"
BOT_USERNAME = "kazumi_group_bot"

[[d1_databases]]
binding = "db"
database_name = "kazumi-group-bot"
database_id = "9e6b3925-d917-4537-a3ff-e780268d0979"

[[r2_buckets]]
bucket_name = "kazumi-captcha"
binding = "captcha"

[[kv_namespaces]]
binding = "aiContext"
id = "dcabc271234f4c4780eff4a64c29a354"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1